apiVersion: v1
kind: Service
metadata:
    labels:
        app: xgb-classifier
    name: xgb-classifier
    namespace: default
spec:
    ports:
    - name: predict
      port: 3000
      targetPort: 3000
    selector:
      app: xgb-classifier
    type: LoadBalancer
    externalIPs:
    - 54.236.84.49
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: xgb-classifier
    name: xgb-classifier
    namespace: default
spec:
    selector:
        matchLabels:
            app: xgb-classifier
    replicas: 2
    template:
        metadata:
            labels:
                app: xgb-classifier
        spec:
            containers:
            - image: devbarahen61/xgb_classifier:latest
              imagePullPolicy: IfNotPresent
              name: xgb-classifier
              ports:
              - containerPort: 3000
